name = "spinmachoapp-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmachoapp.de"
HMAC_KEY = "5d622c3f1bde3d53709e86eee1a8e16468609bb99e700887b275f7cbb4ea37e1"
COOKIE_NAME = "25y"
PLAY_PATH = "start"
BUTTON_ID = "paf3af892115f0faa26ae48493cdd5f14"
GATE_SALT = "6c0ebfc9367d00ae"
